# Generated by AI (UnitTest MCP)
"""Contract tests for delegated intake, observed capacity, and outcome hierarchy."""

from __future__ import annotations

import dataclasses

import pytest

import dream.contracts as contracts
from dream.contracts.delegation import (
    CapacityPort,
    DelegatedIntakePort,
    DelegatedWorkRef,
    DelegatedWorkRequest,
    ProfessionCapacity,
    StaffingBlocked,
    StaffingRequirement,
)
from dream.contracts.strategy import OutcomeEvent


def test_staffing_requirement_defaults_to_one_employee() -> None:
    requirement = StaffingRequirement(profession="engineer")

    assert requirement == StaffingRequirement(profession="engineer", count=1)


def test_staffing_requirement_is_frozen() -> None:
    requirement = StaffingRequirement(profession="engineer")

    with pytest.raises(dataclasses.FrozenInstanceError):
        requirement.count = 2  # type: ignore[misc]


def test_delegated_work_request_defaults_are_backward_safe() -> None:
    request = DelegatedWorkRequest(intent="Ship M8", goal_id="goal-8")

    assert dataclasses.asdict(request) == {
        "intent": "Ship M8",
        "goal_id": "goal-8",
        "priority": "medium",
        "requirements": (),
        "preferred_lead": None,
        "max_team_size": None,
        "spend_limit_cents": None,
        "origin_fingerprint": "",
    }


def test_delegated_work_request_preserves_strategy_constraints() -> None:
    requirements = (
        StaffingRequirement(profession="engineer", count=2),
        StaffingRequirement(profession="designer"),
    )

    request = DelegatedWorkRequest(
        intent="Ship M8",
        goal_id="goal-8",
        priority="high",
        requirements=requirements,
        preferred_lead="employee-1",
        max_team_size=4,
        spend_limit_cents=50_000,
        origin_fingerprint="goal-8:v1",
    )

    assert request == DelegatedWorkRequest(
        intent="Ship M8",
        goal_id="goal-8",
        priority="high",
        requirements=requirements,
        preferred_lead="employee-1",
        max_team_size=4,
        spend_limit_cents=50_000,
        origin_fingerprint="goal-8:v1",
    )


def test_delegated_work_ref_is_frozen() -> None:
    reference = DelegatedWorkRef(
        root_task_id="task-root",
        team_id="team-1",
        lead_id="employee-1",
    )

    with pytest.raises(dataclasses.FrozenInstanceError):
        reference.team_id = "team-2"  # type: ignore[misc]


def test_staffing_blocked_is_a_frozen_typed_result() -> None:
    blocked = StaffingBlocked(goal_id="goal-8", reason="no eligible lead")

    assert dataclasses.asdict(blocked) == {
        "goal_id": "goal-8",
        "reason": "no eligible lead",
        "kind": "staffing_blocked",
    }
    with pytest.raises(dataclasses.FrozenInstanceError):
        blocked.reason = "changed"  # type: ignore[misc]


def test_profession_capacity_preserves_observed_runtime_facts() -> None:
    capacity = ProfessionCapacity(
        profession="engineer",
        eligible=3,
        running=1,
        assigned_nonterminal=2,
        queued_wakes=1,
        budget_blocked=0,
        budget_headroom_cents=75_000,
    )

    assert dataclasses.asdict(capacity) == {
        "profession": "engineer",
        "eligible": 3,
        "running": 1,
        "assigned_nonterminal": 2,
        "queued_wakes": 1,
        "budget_blocked": 0,
        "budget_headroom_cents": 75_000,
    }


class _DelegatedIntakeAdapter:
    def submit_delegated(self, request: DelegatedWorkRequest) -> DelegatedWorkRef:
        return DelegatedWorkRef(
            root_task_id=f"task:{request.goal_id}",
            team_id=f"team:{request.goal_id}",
            lead_id="employee-1",
        )


class _MissingDelegatedSubmit:
    pass


class _CapacityAdapter:
    def snapshot(self) -> tuple[ProfessionCapacity, ...]:
        return ()


class _MissingCapacitySnapshot:
    pass


def test_delegated_intake_port_accepts_structural_adapter() -> None:
    assert isinstance(_DelegatedIntakeAdapter(), DelegatedIntakePort)


def test_delegated_intake_port_rejects_missing_submit_method() -> None:
    assert not isinstance(_MissingDelegatedSubmit(), DelegatedIntakePort)


def test_capacity_port_accepts_structural_adapter() -> None:
    assert isinstance(_CapacityAdapter(), CapacityPort)


def test_capacity_port_rejects_missing_snapshot_method() -> None:
    assert not isinstance(_MissingCapacitySnapshot(), CapacityPort)


def test_new_contracts_are_exported_from_public_package() -> None:
    expected = {
        "CapacityPort",
        "DelegatedIntakePort",
        "DelegatedWorkRef",
        "DelegatedWorkRequest",
        "ProfessionCapacity",
        "StaffingBlocked",
        "StaffingRequirement",
    }

    assert expected <= set(contracts.__all__)


def test_existing_outcome_event_defaults_hierarchy_to_single_task() -> None:
    event = OutcomeEvent(kind="run.done", task_id="task-1")

    assert dataclasses.asdict(event) == {
        "kind": "run.done",
        "task_id": "task-1",
        "goal_id": None,
        "status": None,
        "passed": None,
        "detail": "",
        "parent_task_id": None,
        "root_task_id": None,
        "team_id": None,
        "execution_mode": None,
        "is_root_outcome": False,
        "event_id": None,
        "task_revision": None,
    }


def test_outcome_event_preserves_delegation_hierarchy() -> None:
    event = OutcomeEvent(
        kind="run.done",
        task_id="task-child",
        goal_id="goal-8",
        status="done",
        passed=True,
        parent_task_id="task-root",
        root_task_id="task-root",
        team_id="team-1",
        execution_mode="delivery",
        is_root_outcome=False,
    )

    assert event == OutcomeEvent(
        kind="run.done",
        task_id="task-child",
        goal_id="goal-8",
        status="done",
        passed=True,
        parent_task_id="task-root",
        root_task_id="task-root",
        team_id="team-1",
        execution_mode="delivery",
        is_root_outcome=False,
    )