"""Governance DTOs expose team execution without breaking legacy readers."""

# Generated by AI (UnitTest MCP)

from __future__ import annotations

import dataclasses

from dream.contracts import GovGoal, StaffingRequirement


def test_governance_goal_legacy_defaults_remain_compatible():
    goal = GovGoal(goal_id="goal-1", title="Ship")

    assert goal.task_id is None
    assert goal.delivery_shape == "single"
    assert goal.task_ids == ()
    assert goal.effective_score is None
    assert goal.priority_reason == ""


def test_governance_goal_carries_team_and_effective_priority():
    goal = GovGoal(
        goal_id="goal-1",
        title="Ship",
        score=0.8,
        priority="high",
        effective_score=0.4,
        effective_priority="medium",
        priority_reason="heavy load",
        task_id="root-1",
        root_task_id="root-1",
        task_ids=("root-1", "child-1"),
        team_id="team-1",
        lead_id="lead-1",
        task_outcomes={"child-1": "passed"},
        delivery_shape="team",
        staffing_requirements=(StaffingRequirement("engineer", 2),),
    )

    assert (goal.root_task_id, goal.team_id, goal.lead_id) == (
        "root-1",
        "team-1",
        "lead-1",
    )
    assert (goal.effective_score, goal.effective_priority) == (0.4, "medium")
    assert goal.task_outcomes == {"child-1": "passed"}


def test_gov_goal_task_outcomes_survives_asdict_and_copies_its_input() -> None:
    source = {"child-1": "passed"}
    goal = GovGoal(goal_id="g1", title="Ship", task_outcomes=source)

    source["child-2"] = "failed"  # mutating the caller's dict must not leak into the DTO
    assert goal.task_outcomes == {"child-1": "passed"}

    flat = dataclasses.asdict(goal)  # plain read shape: serialization must just work
    assert flat["task_outcomes"] == {"child-1": "passed"}
